# numpy Operations
  * Lead upto Eigenvalues
  * Connects with PCA (Principal Component Analysis of Machine Learning)

In [1]:
# Import needed modules
import numpy as np

In [2]:
# define a 2D array (3 rows and 2 columns)
data = np.array([[1, 2], [-3, 4], [5, 6]])

In [4]:
print(data)
print("Shape of the array:", data.shape)
print("Data type of the array:", data.dtype)

[[ 1  2]
 [-3  4]
 [ 5  6]]
Shape of the array: (3, 2)
Data type of the array: int64


In [5]:
# Multiplication of the array with a scalar
A = data
B = 2 * A
print("Array A:\n", A)
print("Array B (A multiplied by 2):\n", B)

Array A:
 [[ 1  2]
 [-3  4]
 [ 5  6]]
Array B (A multiplied by 2):
 [[ 2  4]
 [-6  8]
 [10 12]]


In [ ]:
# Multiplication of two arrays (element-wise)
# Note: Both A and B have the same shape, so we can perform element-wise multiplication
C = A * B
print("Element-wise multiplication of A and B (Array C):\n", C)

Element-wise multiplication of A and B (Array C):
 [[ 2  8]
 [18 32]
 [50 72]]


In [8]:
# Multiplication of two matrices (dot product)
# For matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix. 
# Here, A is 3x2 and D is 2x3
D = np.array([[1, 0, 2], [0, 1, 3]])
E = np.dot(A, D)
print("Matrix D:\n", D)
print("Dot product of A and D (Array E):\n", E)

Matrix D:
 [[1 0 2]
 [0 1 3]]
Dot product of A and D (Array E):
 [[ 1  2  8]
 [-3  4  6]
 [ 5  6 28]]


In [ ]:
# another form of matrix multiplication using the @ operator - same result as np.dot
F = A @ D
print("Matrix F (using @ operator for matrix multiplication):\n", F)

Matrix F (using @ operator for matrix multiplication):
 [[ 1  2  8]
 [-3  4  6]
 [ 5  6 28]]
