# numpy Operations
  * Lead upto Eigenvalues
  * Connects with PCA (Principal Component Analysis of Machine Learning)

In [1]:
# Import needed modules
import numpy as np

In [2]:
# define a 2D array (3 rows and 2 columns)
data = np.array([[1, 2], [-3, 4], [5, 6]])

In [4]:
print(data)
print("Shape of the array:", data.shape)
print("Data type of the array:", data.dtype)

[[ 1  2]
 [-3  4]
 [ 5  6]]
Shape of the array: (3, 2)
Data type of the array: int64


In [5]:
# Multiplication of the array with a scalar
A = data
B = 2 * A
print("Array A:\n", A)
print("Array B (A multiplied by 2):\n", B)

Array A:
 [[ 1  2]
 [-3  4]
 [ 5  6]]
Array B (A multiplied by 2):
 [[ 2  4]
 [-6  8]
 [10 12]]


In [ ]:
# Multiplication of two arrays (element-wise)
# Note: Both A and B have the same shape, so we can perform element-wise multiplication
C = A * B
print("Element-wise multiplication of A and B (Array C):\n", C)

Element-wise multiplication of A and B (Array C):
 [[ 2  8]
 [18 32]
 [50 72]]


In [8]:
# Multiplication of two matrices (dot product)
# For matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix. 
# Here, A is 3x2 and D is 2x3
D = np.array([[1, 0, 2], [0, 1, 3]])
E = np.dot(A, D)
print("Matrix D:\n", D)
print("Dot product of A and D (Array E):\n", E)

Matrix D:
 [[1 0 2]
 [0 1 3]]
Dot product of A and D (Array E):
 [[ 1  2  8]
 [-3  4  6]
 [ 5  6 28]]


In [ ]:
# another form of matrix multiplication using the @ operator - same result as np.dot
F = A @ D
print("Matrix F (using @ operator for matrix multiplication):\n", F)

Matrix F (using @ operator for matrix multiplication):
 [[ 1  2  8]
 [-3  4  6]
 [ 5  6 28]]


### Transpose and Inverse of Matrix

In [10]:
# Transpose of a matrix
G = A.T
print("Transpose of Matrix A (Array G):\n", G)

Transpose of Matrix A (Array G):
 [[ 1 -3  5]
 [ 2  4  6]]


In [11]:
# Shape of Transpose of A
print("Shape of Transpose of A (Array G):", G.shape)

Shape of Transpose of A (Array G): (2, 3)


In [13]:
# Inverse of a matrix A - Note: A must be a square matrix and non-singular to have an inverse.
# Since A is 3x2, it does not have an inverse. For demonstration, let's define a square matrix H and compute its inverse.
H = np.array([[1, -3, 5], [2, 4, 6], [0, 1, 2]])

HI = np.linalg.inv(H)
print("Inverse of Matrix H (Array HI):\n", HI)

Inverse of Matrix H (Array HI):
 [[ 0.08333333  0.45833333 -1.58333333]
 [-0.16666667  0.08333333  0.16666667]
 [ 0.08333333 -0.04166667  0.41666667]]


In [14]:
# Matrix multiplication of H and its inverse should yield the identity matrix
Identity = H @ HI
print("Product of H and its inverse (should be identity matrix):\n", Identity)

Product of H and its inverse (should be identity matrix):
 [[ 1.00000000e+00  1.38777878e-17 -5.55111512e-17]
 [ 5.55111512e-17  1.00000000e+00  1.11022302e-16]
 [ 2.77555756e-17 -1.38777878e-17  1.00000000e+00]]


In [15]:
# Determinant of a matrix
det_H = np.linalg.det(H)
print("Determinant of Matrix H:", det_H)

Determinant of Matrix H: 23.999999999999993


### Matrix Transformations

In [20]:
# Matrix transformations - Example: Scaling a matrix by multiplying with a scalar. Each element 
# of the matrix is multiplied by the scalar value.
scalar = 8
scaled_H = scalar * H
print(f"Matrix H:\n", H)
print(f"Matrix H scaled by a factor of {scalar}:\n", scaled_H)

Matrix H:
 [[ 1 -3  5]
 [ 2  4  6]
 [ 0  1  2]]
Matrix H scaled by a factor of 8:
 [[  8 -24  40]
 [ 16  32  48]
 [  0   8  16]]


In [21]:
# Matrix transformations - Example: Adding a scalar to each element of the matrix. 
# Each element of the matrix is increased by the scalar value.
scalar_add = 5
added_H = scalar_add + H
print(f"Matrix H:\n", H)
print(f"Matrix H with scalar {scalar_add} added to each element:\n", added_H)

Matrix H:
 [[ 1 -3  5]
 [ 2  4  6]
 [ 0  1  2]]
Matrix H with scalar 5 added to each element:
 [[ 6  2 10]
 [ 7  9 11]
 [ 5  6  7]]


In [23]:
# Matrix transformations - Example: Scaling a matrix by multiplying with a vector
scale_vector = np.array([2, 3, -1])  # Scale x by 2, y by 3, and z by -1
scaled_H_vector = H @ scale_vector[:, np.newaxis]  # Scale each row of H by the corresponding element in the scale_vector
print(f"Matrix H:\n", H)
print(f"Matrix H scaled by vector {scale_vector}:\n", scaled_H_vector)

Matrix H:
 [[ 1 -3  5]
 [ 2  4  6]
 [ 0  1  2]]
Matrix H scaled by vector [ 2  3 -1]:
 [[-12]
 [ 10]
 [  1]]


### Scaling - how it works with scale vector [2, 3, -1]
Columns:  X ------ Y ------ Z<br>
Row 0:  (1×2) + (-3×3) + (5×-1)  =  2 - 9 - 5  = -12<br>
Row 1:  (2×2) + ( 4×3) + (6×-1)  =  4 + 12 - 6 =  10<br>
Row 2:  (0×2) + ( 1×3) + (2×-1)  =  0 +  3 - 2 =   1<br>
- col x scaled by 2, 
- col y scaled by 3
- col z scaled by -1
